# Generated by Django 5.0.1 on 2026-05-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=100)),
                ("query", models.CharField(max_length=500)),
                ("results_count", models.IntegerField(default=0)),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
                ("device", models.CharField(blank=True, max_length=50, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("title", models.CharField(default="Untitled", max_length=500)),
                (
                    "category",
                    models.CharField(db_index=True, default="General", max_length=200),
                ),
                ("categories", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("features", models.TextField(blank=True, null=True)),
                ("price", models.FloatField(blank=True, null=True)),
                ("avg_rating", models.FloatField(default=0.0)),
                ("rating_count", models.IntegerField(default=0)),
                ("store", models.CharField(blank=True, max_length=200, null=True)),
                ("details", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["category"], name="recommender_categor_f3c857_idx"
                    ),
                    models.Index(
                        fields=["avg_rating"], name="recommender_avg_rat_39887b_idx"
                    ),
                    models.Index(fields=["price"], name="recommender_price_ae8a73_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserBrowsingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=100)),
                ("item_id", models.CharField(db_index=True, max_length=50)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("click", "Click"),
                            ("add_to_cart", "Add to Cart"),
                            ("remove_from_cart", "Remove from Cart"),
                            ("search", "Search"),
                        ],
                        max_length=20,
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
                ("device", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("homepage", "Homepage"),
                            ("search", "Search"),
                            ("recommendation", "Recommendation"),
                            ("category", "Category"),
                            ("direct", "Direct"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user_id", "timestamp"],
                        name="recommender_user_id_0602cf_idx",
                    ),
                    models.Index(
                        fields=["item_id"], name="recommender_item_id_2db5cb_idx"
                    ),
                    models.Index(
                        fields=["session_id"], name="recommender_session_253e9c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=100)),
                ("item_id", models.CharField(db_index=True, max_length=50)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("review_text", models.TextField(blank=True, null=True)),
                (
                    "review_title",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("verified", models.BooleanField(default=False)),
                ("helpful_votes", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["item_id", "timestamp"],
                        name="recommender_item_id_75111c_idx",
                    ),
                    models.Index(
                        fields=["user_id", "timestamp"],
                        name="recommender_user_id_d624a0_idx",
                    ),
                ],
            },
        ),
    ]
