# Generated by Django 5.0.1 on 2026-05-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommender", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="image_url",
        ),
        migrations.AddField(
            model_name="item",
            name="bought_together",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="images",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="videos",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userinteraction",
            name="images",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userinteraction",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
