"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-s*36+fr5czna-mu)m3h@)a04phu6*)smhynd65&t64$33g0*fk"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    "recommender"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ─── Logging ──────────────────────────────────────────────────────────────────

import os as _os
_LOGS_DIR = BASE_DIR / "logs"
_LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style":  "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "interaction": {
            # Compact single-line format for the interactions log
            "format": "{asctime} | {message}",
            "style":  "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },

    "handlers": {
        # Console — all DEBUG+ messages
        "console": {
            "class":     "logging.StreamHandler",
            "formatter": "verbose",
            "level":     "DEBUG",
        },
        # General application log
        "app_file": {
            "class":       "logging.handlers.RotatingFileHandler",
            "filename":    str(_LOGS_DIR / "app.log"),
            "maxBytes":    5 * 1024 * 1024,   # 5 MB
            "backupCount": 3,
            "formatter":   "verbose",
            "level":       "INFO",
            "encoding":    "utf-8",
        },
        # User-interaction events log (views, clicks, ratings, searches)
        "interactions_file": {
            "class":       "logging.handlers.RotatingFileHandler",
            "filename":    str(_LOGS_DIR / "interactions.log"),
            "maxBytes":    10 * 1024 * 1024,  # 10 MB
            "backupCount": 5,
            "formatter":   "interaction",
            "level":       "INFO",
            "encoding":    "utf-8",
        },
        # ML pipeline log (training, evaluation, retraining)
        "ml_file": {
            "class":       "logging.handlers.RotatingFileHandler",
            "filename":    str(_LOGS_DIR / "ml.log"),
            "maxBytes":    10 * 1024 * 1024,
            "backupCount": 3,
            "formatter":   "verbose",
            "level":       "INFO",
            "encoding":    "utf-8",
        },
    },

    "loggers": {
        # Django internals
        "django": {
            "handlers": ["console", "app_file"],
            "level":    "INFO",
            "propagate": False,
        },
        # User interaction events (tracking, browsing, ratings)
        "recommender.interactions": {
            "handlers": ["interactions_file", "console"],
            "level":    "INFO",
            "propagate": False,
        },
        # ML layer (training, inference, pipelines)
        "ml": {
            "handlers": ["ml_file", "console"],
            "level":    "INFO",
            "propagate": False,
        },
        # Recommender app (views, services)
        "recommender": {
            "handlers": ["app_file", "console"],
            "level":    "INFO",
            "propagate": False,
        },
        # Root logger — catch everything else
        "": {
            "handlers": ["console", "app_file"],
            "level":    "WARNING",
        },
    },
}


# ─── MLflow ───────────────────────────────────────────────────────────────────

MLFLOW_TRACKING_URI = str(BASE_DIR / "mlruns")
